### ISSUE TITLE
JPG Identified as MP3

### ISSUE THREAD

**Issue by chriscrowley** [MediatedCommunications/Mime-Detective#58]
This JPG file is being identified as a MP3 file in these versions: 24.12.1, 24.12.2, 25.4.15, and 25.4.25
![Image](https://github.com/user-attachments/assets/d8f27f7d-dd25-442f-859e-836b3ad89d35)

**Comment by TonyValenti** [comment]
Which set of definitions are you using?

**Comment by chriscrowley** [comment]
Default Definitions.

**Comment by TonyValenti** [comment]
This will likely be fixed in an update coming a few days after the next .NET update.

**Comment by chriscrowley** [comment]
Does commit c207a90 address this problem?
When will this update be available through NuGet?

**Comment by markmccaigue** [comment]
> Does commit [c207a90](https://github.com/MediatedCommunications/Mime-Detective/commit/c207a905a6238b7af98b18bee1a3daabeae58490) address this problem? When will this update be available through NuGet?

We've hit a similar issue with a JPG being detected as an MP3, and I was also wondering if a version including this commit may help, and if it could be made available via Nuget? Many thanks

**Comment by TonyValenti** [comment]
Hi All! Sorry about the delay.  I was OOO on vacation last week.
I have just pushed an update that includes updated signatures.  If you're running into any issues, just open a new issue and I'll take a look.

**Comment by molinch** [comment]
@TonyValenti the issue is still present with [25.8.1](https://www.nuget.org/packages/Mime-Detective/25.8.1)
