### ISSUE TITLE
Getting SGEN : error : An attempt was made to load an assembly with an incorrect format: C:\Users\IgorPietraszko\.nuget\packages\system.buffers\4.5.1\ref\net45\System.Buffers.dll.

### ISSUE THREAD

**Issue by IgorPietraszko** [MediatedCommunications/Mime-Detective#7]
Seems to be hanging up on the System.Buffers assembly 4.5.1 reference when doing a NANT build.  Seem to be building fine locally.  Is it possible to clone your project and rebuild it myself as a project?

**Comment by TonyValenti** [comment]
Let me dig and and see what's up. What .Net version are you using?

**Comment by TonyValenti** [comment]
I think I know what the issue is.  I'll publish an update tomorrow.

**Comment by IgorPietraszko** [comment]
Thanks, that would be great.  Let me know.

Igor

**Comment by TonyValenti** [comment]
What version?  Are you.net 5?

**Comment by IgorPietraszko** [comment]
No, .Net 4.8

**Comment by TonyValenti** [comment]
I just Pushed an update but I'm not positive this has the fix. 

Was the library working and then it stopped or did it never work?

**Comment by IgorPietraszko** [comment]
Never got to test it. Built fine locally but failed to build using the NANT
script. If it builds with NANT now I will test it.

Did you gen a new NuGet?

Igor

**Comment by TonyValenti** [comment]
Yes.  I pushed a new package this morning.

**Comment by IgorPietraszko** [comment]
Sorry Tony, still no go on NANT script based build.  Same compliant:

[image: image.png]

I think it's related to the embedded use of SystemBuffers 4.5.1

[image: image.png]

I can't change the targeting framework easily - its a large project and
that would be a big change.  But it also does not complain about anything
else - just this one assembly.

Igor

**Comment by TonyValenti** [comment]
If you can figure it out, I'd love to know what the issue is.  This is the first time the issue has been reported.
